// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpcproto/chat.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_grpcproto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_grpcproto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpcproto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcproto_chat_proto_rawDescGZIP(), []int{1}
}

var File_grpcproto_chat_proto protoreflect.FileDescriptor

const file_grpcproto_chat_proto_rawDesc = "" +
	"\n" +
	"\x14grpcproto/chat.proto\x12\x04chat\"!\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"\a\n" +
	"\x05Empty2v\n" +
	"\vChatService\x122\n" +
	"\x10BroadcastMessage\x12\x11.chat.ChatMessage\x1a\v.chat.Empty\x123\n" +
	"\x0fReceiveMessages\x12\v.chat.Empty\x1a\x11.chat.ChatMessage0\x01B8Z6github.com/TusharSindhu/LetsGoChat/grpcproto;grpcprotob\x06proto3"

var (
	file_grpcproto_chat_proto_rawDescOnce sync.Once
	file_grpcproto_chat_proto_rawDescData []byte
)

func file_grpcproto_chat_proto_rawDescGZIP() []byte {
	file_grpcproto_chat_proto_rawDescOnce.Do(func() {
		file_grpcproto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproto_chat_proto_rawDesc), len(file_grpcproto_chat_proto_rawDesc)))
	})
	return file_grpcproto_chat_proto_rawDescData
}

var file_grpcproto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcproto_chat_proto_goTypes = []any{
	(*ChatMessage)(nil), // 0: chat.ChatMessage
	(*Empty)(nil),       // 1: chat.Empty
}
var file_grpcproto_chat_proto_depIdxs = []int32{
	0, // 0: chat.ChatService.BroadcastMessage:input_type -> chat.ChatMessage
	1, // 1: chat.ChatService.ReceiveMessages:input_type -> chat.Empty
	1, // 2: chat.ChatService.BroadcastMessage:output_type -> chat.Empty
	0, // 3: chat.ChatService.ReceiveMessages:output_type -> chat.ChatMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcproto_chat_proto_init() }
func file_grpcproto_chat_proto_init() {
	if File_grpcproto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproto_chat_proto_rawDesc), len(file_grpcproto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproto_chat_proto_goTypes,
		DependencyIndexes: file_grpcproto_chat_proto_depIdxs,
		MessageInfos:      file_grpcproto_chat_proto_msgTypes,
	}.Build()
	File_grpcproto_chat_proto = out.File
	file_grpcproto_chat_proto_goTypes = nil
	file_grpcproto_chat_proto_depIdxs = nil
}
